/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vvote.h"

bool_t
xdr_Candidate(xdrs, objp)
	XDR *xdrs;
	Candidate *objp;
{

	if (!xdr_String(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->votes))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->next, sizeof(Candidate), (xdrproc_t)xdr_Candidate))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Voter(xdrs, objp)
	XDR *xdrs;
	Voter *objp;
{

	if (!xdr_int(xdrs, &objp->id))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->voted))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->next, sizeof(Voter), (xdrproc_t)xdr_Voter))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_changepassword_1_argument(xdrs, objp)
	XDR *xdrs;
	changepassword_1_argument *objp;
{
	if (!xdr_string(xdrs, &objp->arg1, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->arg2, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->arg3, ~0))
		return (FALSE);
	return (TRUE);
}
