/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VVOTE_H_RPCGEN
#define _VVOTE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct Candidate {
	String name;
	int votes;
	struct Candidate *next;
};
typedef struct Candidate Candidate;
#ifdef __cplusplus
extern "C" bool_t xdr_Candidate(XDR *, Candidate*);
#elif __STDC__
extern  bool_t xdr_Candidate(XDR *, Candidate*);
#else /* Old Style C */
bool_t xdr_Candidate();
#endif /* Old Style C */


struct Voter {
	int id;
	short voted;
	struct Voter *next;
};
typedef struct Voter Voter;
#ifdef __cplusplus
extern "C" bool_t xdr_Voter(XDR *, Voter*);
#elif __STDC__
extern  bool_t xdr_Voter(XDR *, Voter*);
#else /* Old Style C */
bool_t xdr_Voter();
#endif /* Old Style C */


struct changepassword_1_argument {
	char *arg1;
	char *arg2;
	char *arg3;
};
typedef struct changepassword_1_argument changepassword_1_argument;
#ifdef __cplusplus
extern "C" bool_t xdr_changepassword_1_argument(XDR *, changepassword_1_argument);
#elif __STDC__
extern  bool_t xdr_changepassword_1_argument(XDR *, changepassword_1_argument);
#else /* Old Style C */
bool_t xdr_changepassword_1_argument();
#endif /* Old Style C */


#define VOTINGSYS ((rpc_uint)0x2fffffff)
#define VOTINGSYS_V1 ((rpc_uint)1)

#ifdef __cplusplus
#define changepassword ((rpc_uint)1)
extern "C" char ** changepassword_1(char *, char *, char *, CLIENT *);
extern "C" char ** changepassword_1_svc(char *, char *, char *, struct svc_req *);

#elif __STDC__
#define changepassword ((rpc_uint)1)
extern  char ** changepassword_1(char *, char *, char *, CLIENT *);
extern  char ** changepassword_1_svc(char *, char *, char *, struct svc_req *);

#else /* Old Style C */
#define changepassword ((rpc_uint)1)
extern  char ** changepassword_1();
extern  char ** changepassword_1_svc();
#endif /* Old Style C */

#endif /* !_VVOTE_H_RPCGEN */
