#compiler flags:
CFLAGS = -g

#target directory
bin = ../bin

server-tcp: server-tcp.c
	gcc -o $(bin)/server-tcp -g server-tcp.c

server-udp: server-udp.c
	gcc -o $(bin)/server-udp -g server-udp.c

add-voter-tcp: add-voter-tcp.c
	gcc -o $(bin)/add-voter-tcp -g add-voter-tcp.c

add-voter-udp: add-voter-udp.c
	gcc -o $(bin)/add-voter-udp -g add-voter-udp.c

change-password-tcp: change-password-tcp.c
	gcc -o $(bin)/change-password-tcp -g change-password-tcp.c

change-password-udp: change-password-udp.c
	gcc -o $(bin)/change-password-udp -g change-password-udp.c

list-candidates-tcp: list-candidates-tcp.c
	gcc -o $(bin)/list-candidates-tcp -g list-candidates-tcp.c

list-candidates-udp: list-candidates-udp.c
	gcc -o $(bin)/list-candidates-udp -g list-candidates-udp.c

view-result-tcp: view-result-tcp.c
	gcc -o $(bin)/view-result-tcp -g view-result-tcp.c

view-result-udp: view-result-udp.c
	gcc -o $(bin)/view-result-udp -g view-result-udp.c

vote-count-tcp: vote-count-tcp.c
	gcc -o $(bin)/vote-count-tcp -g vote-count-tcp.c

vote-count-udp: vote-count-udp.c
	gcc -o $(bin)/vote-count-udp -g vote-count-udp.c

vote-tcp: vote-tcp.c
	gcc -o $(bin)/vote-tcp -g vote-tcp.c

vote-udp: vote-udp.c
	gcc -o $(bin)/vote-udp -g vote-udp.c

vote-zero-tcp: vote-zero-tcp.c
	gcc -o $(bin)/vote-zero-tcp -g vote-zero-tcp.c

vote-zero-udp: vote-zero-udp.c
	gcc -o $(bin)/vote-zero-udp -g vote-zero-udp.c
